services:
  weather-app:
    image: 1ezhevika1/weather-app:latest
    container_name: weather-app
    restart: unless-stopped
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    expose:
      - "5000"
    networks:
      - weather-network

  nginx:
    image: nginx:alpine
    container_name: weather-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - weather-app
    networks:
      - weather-network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_NO_RESTART=false
    command: --interval 60 --cleanup weather-app
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge